- hosts: VM-2
  become: yes
  tasks:
    - name: Install Apache2 on Ubuntu
      apt:
        name: apache2
        state: present
      vars:
        ansible_python_interpreter: /usr/bin/python3  # Specify Python 3 interpreter if needed
