- hosts: VM-2
  become: yes
  tasks:
    - name: Perform system updates with a delay
      apt:
        upgrade: yes
        update_cache: yes
      async: 600  # Wait for 600 seconds (10 minutes)
      poll: 0
