---
- name: Uninstall Nginx on VM-2
  hosts: VM-2
  become: yes  # This will run the tasks with escalated privileges

  tasks:
    - name: Uninstall Nginx On Ubuntu Server
      apt:
        name: nginx
        state: absent
