- hosts: Mac
  tasks:
    - name: Stop Portainer
      become: no  # Disable privilege escalation for this task
      environment:
        PATH: "/usr/local/bin:/usr/bin:/bin"
      command: "docker stop portainer"
